### 1. What is NumPy
### 2. Why NumPy is faster
### 3. Creating arrays
### 4. Random numbers
### 5. Array attributes
### 6. Indexing + slicing
### 7. Arithmetic operations
### 8. Matrix multiplication / dot
### 9. Helper functions
### 10. Boolean & fancy indexing

### Numpy

### NumPy is a popular Python library used for working with numbers. It lets you create large arrays (lists of numbers) and do math on them very quickly. It’s faster than normal Python lists because the numbers are stored in one continuous place in memory, which makes calculations efficient. Most data science and machine learning tools use NumPy at the core for handling numerical data.

In [23]:
!pip install numpy

In [24]:
import numpy as np 
arr=np.array([1,2,3,4])

In [25]:
arr

array([1, 2, 3, 4])

In [26]:
arr.ndim

1

In [71]:
a8=np.array([1,2,3,4,5,6,7,8,9,0])
a8[a8>5]

array([6, 7, 8, 9])

In [28]:
arr.reshape((1,4))

array([[1, 2, 3, 4]])

In [37]:
## array attributes
arr1=np.array([[1,2,3],[4,5,6]])
print(" array :" , arr1)
print("shape :",arr.shape)
print("size of the array", arr.size)
print("datatype",arr.dtype)


 array : [[1 2 3]
 [4 5 6]]
shape : (4,)
size of the array 4
datatype int64


In [39]:
## maths function
arr2=np.array([1,2,3,4])
print(np.sqrt(arr2))


print(np.log(arr2))
print(np.sin(arr2))
print(np.exp(arr2))

[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [40]:
arr3=np.array([1,2,3,4])
mean=np.mean(arr3)

In [41]:
mean

2.5

In [44]:
print(np.median(arr3))
print(np.std(arr3))
print(np.var(arr3))

2.5
1.118033988749895
1.25


In [46]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
arr4[1,0]

4

In [54]:
arr4[1:,1:]

array([[5, 6],
       [8, 9]])

In [55]:
### arithmetic operations
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,0])
print("addition: ",a1+a2)
print("sub:" ,a1-a2)
print("multiply: ",a1*a2)
print("division :",a1/a2)

addition:  [ 7  9 11 13  5]
sub: [-5 -5 -5 -5  5]
multiply:  [ 6 14 24 36  0]
division : [0.16666667 0.28571429 0.375      0.44444444        inf]


/var/folders/4v/jwyz348j77d99rpv6cwvqrm40000gn/T/ipykernel_9530/2729279218.py:7: RuntimeWarning: divide by zero encountered in divide
  print("division :",a1/a2)


In [57]:
arr5=np.array([2,2,3,4,5,4,6])
print(np.sum(arr5))

26


In [58]:
print(np.sort(arr5))

[2 2 3 4 4 5 6]


In [59]:
print(np.unique(arr5))

[2 3 4 5 6]


In [65]:
np.random.rand(3,3)       # uniform 0-1

array([[0.93747791, 0.95840185, 0.65243775],
       [0.69202784, 0.30316502, 0.13117762],
       [0.00449377, 0.89049141, 0.87819183]])

In [67]:
np.random.randn(3,3)      # normal distribution

array([[ 0.97237955, -2.31857108,  0.44930908],
       [-1.46081167, -1.52982553, -0.50571426],
       [-0.02201333,  0.27862917, -2.54344684]])

In [69]:
np.random.randint(1,100,5) # random ints

array([57,  7, 59, 39, 47])